### ISSUE TITLE
Link-Parameter not working

### ISSUE THREAD

**Issue by jannickfahlbusch** [hamstah/clouddream#2]
Every time i try to start clouddream, Docker throws the follwing errors:

```
invalid value "deepdream-redis" for flag --link: Invalid format to parse.  deepdream-redis should match template name:alias
See 'docker run --help'.
invalid value "deepdream-redis" for flag --link: Invalid format to parse.  deepdream-redis should match template name:alias
See 'docker run --help'.
invalid value "deepdream-manager" for flag --link: Invalid format to parse.  deepdream-manager should match template name:alias
See 'docker run --help'.
```

`./start.sh` only starts the first container, all other are throwing the errors above.

Any idea, how to solve this problem?

**Comment by hamstah** [comment]
Sorry I haven't removed start.sh.

Try running with docker compose instead

docker-compose up

Should work

**Comment by jannickfahlbusch** [comment]
WOW! That was a fast response!

Thanks, it works for now :)
